version: "3.9"
services:
  breast_cancer_model:
    image: breast_cancer_model:xception-v4-001
  gateway:
    image: breast_cancer_gateway:001
    environment:
      - TF_SERVING_HOST=breast_cancer_model:8500
    ports:
      - "9696:9696"